### ISSUE TITLE
Unable to load addon

### ISSUE THREAD

**Issue by cosmin-novac** [Tshmofen/waterways-net#6]
When I try to activate this in Godot 4.3, I receive:

Unable to load addon script from path: 'res://addons/waterways_net/WaterwaysPlugin.cs'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/waterways_net/plugin.cfg' to prevent further errors.

**Comment by Tshmofen** [comment]
@cosmin-novac Addod defenitely works for me on 4.3, seems like an environment issue. Have you ensured that you did everything from the FAQ point in `readme.md`? - likely solution is just not set up correctly:

# FAQ
* Addon is throwing errors when I'm trying to enable it, what should I do?
  * It's likely the aftermath of using .NET version of Godot. First of all be sure that you've created a solution with `Project` -> `Tools` -> `C#` -> `Create C# Solution` and make sure that it is using `.NET 8.0` (in `.csproj`). After that just build the project and it will generate .NET binaries, now reload Godot and enable the addon - it should now read the scripts correctly.

Let me know if it doesn't help or you have already done that (in that case please also provide contents of  `project.godot` and `*.csproj`).

**Comment by cosmin-novac** [comment]
Hi Tshmofen, I am actually not using the C+ / .NET version.

**Comment by Tshmofen** [comment]
@cosmin-novac Unfortunately this addon is only for .NET version of Godot, you can't use it with default one
