### ISSUE TITLE
Build and export game

### ISSUE THREAD

**Issue by slakibk** [Tshmofen/waterways-net#9]
Errors appear when compiling the game:
![image](https://github.com/user-attachments/assets/9f3234dd-4342-430a-a47f-a0854d388117)

What settings are needed to export the project?

Godot Engine v4.2.2.stable.mono.official.15073afe3 - https://godotengine.org
Vulkan API 1.3.280 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 4070

**Comment by Tshmofen** [comment]
@slakibk Indeed, only tested exports a few updates ago before the rework, and competely forgot to exclude some hard editor references :sweat_smile:

Anyway, the latest [v1.0.1](https://github.com/Tshmofen/waterways-net/releases/tag/v1.0.1) release should fix your issue. Let me know if any functionality is not working as expected on exported build, thanks for opening this issue :)

**Comment by mefjak** [comment]
oh man - I just yesterday added your plugin and wanted to export and had the same problem with 4.3-mono but 1.0.1 works and know I can export :) 

The only issue I see now there is a "Build failure" alert but it exported game and it worked. Maybe something on my side.

**Comment by Tshmofen** [comment]
@mefjak Good to hear it worked for you! 

Also, did a clean test with 1.0.1 and Godot 4.3 - export was done without any warnings/errors. It seems `Build failure` is likely somewhere on your end, hope it hepls to narrow it down :)

**Comment by mefjak** [comment]
Thanks. Sure did :)
